# Generated by Django 3.0.5 on 2020-12-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emaillist_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
