# Generated by Django 3.0.5 on 2020-12-02 10:17

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20200926_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url_video',
            field=embed_video.fields.EmbedVideoField(blank=True, max_length=2083, null=True),
        ),
    ]
